export const hobbiesList = {
  "Sports & Fitness": [
    "Running",
    "Swimming",
    "Cycling",
    "Weightlifting",
    "Yoga",
    "Pilates",
    "Basketball",
    "Soccer",
    "Tennis",
    "Golf",
    "Hiking",
    "Rock Climbing",
    "Skiing",
    "Snowboarding",
    "Surfing",
  ],
  "Arts & Crafts": [
    "Painting",
    "Drawing",
    "Sculpting",
    "Pottery",
    "Knitting",
    "Crocheting",
    "Embroidery",
    "Scrapbooking",
    "Jewelry Making",
    "Woodworking",
    "Origami",
    "Calligraphy",
    "Sewing",
    "Candle Making",
    "Soap Making",
  ],
  "Music & Dance": [
    "Playing an Instrument",
    "Singing",
    "DJing",
    "Composing Music",
    "Ballroom Dancing",
    "Salsa Dancing",
    "Hip Hop Dancing",
    "Ballet",
    "Tap Dancing",
    "Swing Dancing",
    "Line Dancing",
    "Belly Dancing",
    "Irish Dancing",
    "Bollywood Dancing",
    "Flamenco Dancing",
  ],
  "Games & Puzzles": [
    "Chess",
    "Go",
    "Bridge",
    "Poker",
    "Board Games",
    "Jigsaw Puzzles",
    "Crossword Puzzles",
    "Sudoku",
    "Rubik's Cube",
    "Escape Rooms",
    "Video Games",
    "Role-playing Games",
    "Collectible Card Games",
    "Tabletop Wargaming",
    "Miniature Painting",
  ],
  "Outdoor Adventures": [
    "Camping",
    "Backpacking",
    "Fishing",
    "Hunting",
    "Canoeing",
    "Kayaking",
    "Rafting",
    "Sailing",
    "Scuba Diving",
    "Skydiving",
    "Bungee Jumping",
    "Paragliding",
    "Hang Gliding",
    "Geocaching",
    "Orienteering",
  ],
  "Food & Drink": [
    "Cooking",
    "Baking",
    "Grilling",
    "Wine Tasting",
    "Beer Tasting",
    "Whiskey Tasting",
    "Mixology",
    "Coffee Roasting",
    "Tea Tasting",
    "Cheese Making",
    "Sushi Making",
    "Cake Decorating",
    "Bread Making",
    "Pickling",
    "Fermentation",
  ],
  "Languages & Cultures": [
    "Learning a New Language",
    "Traveling",
    "Studying Abroad",
    "Hosting International Students",
    "Attending Cultural Festivals",
    "Participating in Language Exchanges",
    "Collecting Souvenirs from Different Countries",
    "Trying Authentic Cuisine from Various Cultures",
    "Watching Foreign Films",
    "Reading World Literature",
    "Practicing Calligraphy in Different Scripts",
    "Exploring Genealogy and Family History",
    "Volunteering for Cultural Organizations",
    "Attending Museum Exhibitions",
    "Participating in Reenactments or Historical Societies",
  ],
  "Technology & Science": [
    "Programming",
    "Web Development",
    "App Development",
    "Game Development",
    "Robotics",
    "Electronics",
    "3D Printing",
    "Astronomy",
    "Microscopy",
    "Fossil Hunting",
    "Rockhounding",
    "Meteorology",
    "Amateur Radio",
    "Drone Flying",
    "Rocketry",
  ],
  Collecting: [
    "Stamps",
    "Coins",
    "Vinyl Records",
    "Comic Books",
    "Trading Cards",
    "Action Figures",
    "Dolls",
    "Postcards",
    "Shells",
    "Minerals",
    "Fossils",
    "Antiques",
    "Vintage Clothing",
    "Movie Memorabilia",
    "Sports Memorabilia",
  ],
  "Performing Arts": [
    "Acting",
    "Stand-up Comedy",
    "Improv",
    "Storytelling",
    "Mime",
    "Puppetry",
    "Ventriloquism",
    "Magic",
    "Juggling",
    "Fire Spinning",
    "Poi Spinning",
    "Hula Hooping",
    "Aerial Silks",
    "Trapeze",
    "Circus Arts",
  ],
};

export const educationList = [
  "No formal education",
  "Primary school",
  "Middle school",
  "High school",
  "Vocational school",
  "Some college, no degree",
  "Associate degree",
  "Bachelor's degree",
  "Master's degree",
  "Doctoral degree",
  "Professional degree",
];

export const occupationList = [
  { title: "Accountant", category: "Business & Finance" },
  { title: "Business Analyst", category: "Business & Finance" },
  { title: "Consultant", category: "Business & Finance" },
  { title: "Entrepreneur", category: "Business & Finance" },
  { title: "Financial Advisor", category: "Business & Finance" },
  { title: "Human Resources Manager", category: "Business & Finance" },
  { title: "Marketing Manager", category: "Business & Finance" },
  { title: "Product Manager", category: "Business & Finance" },
  { title: "Project Manager", category: "Business & Finance" },
  { title: "Sales Manager", category: "Business & Finance" },
  { title: "Data Analyst", category: "Technology" },
  { title: "Programmer", category: "Technology" },
  { title: "Software Developer", category: "Technology" },
  { title: "UX Designer", category: "Technology" },
  { title: "Web Developer", category: "Technology" },
  { title: "Dentist", category: "Healthcare" },
  { title: "Doctor", category: "Healthcare" },
  { title: "Nurse", category: "Healthcare" },
  { title: "Occupational Therapist", category: "Healthcare" },
  { title: "Pharmacist", category: "Healthcare" },
  { title: "Physical Therapist", category: "Healthcare" },
  { title: "Psychologist", category: "Healthcare" },
  { title: "Registered Nurse", category: "Healthcare" },
  { title: "Veterinarian", category: "Healthcare" },
  { title: "Actor", category: "Arts & Design" },
  { title: "Artist", category: "Arts & Design" },
  { title: "Designer", category: "Arts & Design" },
  { title: "Graphic Designer", category: "Arts & Design" },
  { title: "Hair Stylist", category: "Arts & Design" },
  { title: "Makeup Artist", category: "Arts & Design" },
  { title: "Photographer", category: "Arts & Design" },
  { title: "Video Editor", category: "Arts & Design" },
  { title: "Librarian", category: "Education & Social Services" },
  { title: "Social Worker", category: "Education & Social Services" },
  { title: "Teacher", category: "Education & Social Services" },
  { title: "Translator", category: "Education & Social Services" },
  { title: "Yoga Instructor", category: "Education & Social Services" },
  { title: "Architect", category: "Engineering & Architecture" },
  { title: "Electrician", category: "Engineering & Architecture" },
  { title: "Engineer", category: "Engineering & Architecture" },
  { title: "Attorney", category: "Legal" },
  { title: "Lawyer", category: "Legal" },
  { title: "Editor", category: "Media & Communication" },
  { title: "Journalist", category: "Media & Communication" },
  { title: "Public Relations Specialist", category: "Media & Communication" },
  { title: "Social Media Manager", category: "Media & Communication" },
  { title: "Writer", category: "Media & Communication" },
  { title: "Bartender", category: "Service Industry" },
  { title: "Chef", category: "Service Industry" },
  { title: "Customer Service Representative", category: "Service Industry" },
  { title: "Event Planner", category: "Service Industry" },
  { title: "Real Estate Agent", category: "Service Industry" },
  { title: "Mechanic", category: "Skilled Trades" },
  { title: "Plumber", category: "Skilled Trades" },
  { title: "Firefighter", category: "Public Service & Safety" },
  { title: "Police Officer", category: "Public Service & Safety" },
  { title: "Pilot", category: "Transportation" },
];

