import AcUnitOutlinedIcon from '@mui/icons-material/AcUnitOutlined';
import LocalParkingOutlinedIcon from '@mui/icons-material/LocalParkingOutlined';
import BalconyOutlinedIcon from '@mui/icons-material/BalconyOutlined';
import ChairOutlinedIcon from '@mui/icons-material/ChairOutlined';
import ElevatorOutlinedIcon from "@mui/icons-material/ElevatorOutlined";
import PetsOutlinedIcon from '@mui/icons-material/PetsOutlined';
import SmokingRoomsOutlinedIcon from '@mui/icons-material/SmokingRoomsOutlined';

export const detailsList = [
  { name: "AC", id: "heating", icon: AcUnitOutlinedIcon },
  { name: "Parking", id: "parking", icon: LocalParkingOutlinedIcon },
  { name: "Balcony", id: "balcony", icon: BalconyOutlinedIcon },
  { name: "Furnished", id: "furnished", icon: ChairOutlinedIcon },
  { name: "Elevator", id: "elevator", icon: ElevatorOutlinedIcon },
  { name: "Pet Friendly", id: "petFriendly", icon: PetsOutlinedIcon },
  { name: "Smoking Allowed", id: "smokingAllowed", icon: SmokingRoomsOutlinedIcon },
];

export const amenitiesList = {
  "Internet & Tech": [
    "High-speed Wi-Fi",
    "Smart Home Technology",
    "Keyless Entry",
    "Smart Locks",
    "Smart Lighting",
    "Thermostat Control",
    "USB Charging Ports",
    "Fiber Optic Internet",
    "Multiple Ethernet Ports",
    "Smart TV in Common Area",
    "Gaming Console",
    "Dedicated Workspace with Ergonomic Setup",
    "Printer/Scanner",
    "Soundbar System",
  ],
  "Climate Control": [
    "Individual Room Temperature Control",
    "Air Conditioning",
    "Ceiling Fans",
    "Fireplace",
    "Air Purifiers",
    "Humidifiers/Dehumidifiers",
    "Double-Pane Windows for Insulation",
  ],
  Laundry: [
    "In-Unit Washer/Dryer",
    "Laundry Room",
    "Clothes Drying Rack",
    "Ironing Board and Iron",
    "Laundry Detergent Subscription",
    "Laundry Scheduling App",
  ],
  Kitchen: [
    "Dishwasher",
    "Microwave",
    "Refrigerator with Water/Ice Dispenser",
    "Stove/Oven",
    "Garbage Disposal",
    "Granite Countertops",
    "Community Kitchen",
    "Coffee Bar",
    "Pantry Space",
    "Individual Food Storage Areas",
    "Multiple Mini-Fridges",
    "Shared Cooking Utensils and Appliances",
    "Meal Prep Station",
    "Labeled Storage Containers",
    "Whiteboard for Grocery Lists",
  ],
  Outdoor: [
    "Balcony/Patio",
    "BBQ Area",
    "Roof Deck",
    "Garden/Courtyard",
    "Outdoor Seating Areas",
    "Pet Areas",
    "Hammocks",
    "Outdoor Movie Projection Screen",
    "Communal Fire Pit",
    "Bike Racks",
    "Outdoor Workout Area",
  ],
  "Security & Access": [
    "24/7 Security",
    "Bike Storage",
    "Electric Vehicle Charging Stations",
    "Guest Parking",
    "Package Lockers",
    "Security Cameras",
    "Intercom System",
    "Fob Access to Common Areas",
    "Secure Mail Room",
    "Guest Check-In System",
  ],
  "Living Space": [
    "Shared Living Space",
    "Private Bedrooms",
    "Private Bathrooms",
    "Storage Units",
    "High Ceilings",
    "Plank Flooring",
    "Built-In Shelving",
    "Mudroom",
    "Soundproof Walls",
    "Flexible Furniture Arrangements",
    "Room Dividers for Privacy",
    "Blackout Curtains",
    "Individual Thermostats",
    "Personal Safes",
    "Noise-Cancelling Headphones",
  ],
  Convenience: [
    "Utilities Included",
    "Weekly Cleaning Service",
    "On-Site Recycling",
    "Virtual Concierge",
    "Community Social Events",
    "Roommate Matching Service",
    "Shared Household Items Inventory",
    "Chore Schedule App",
    "Grocery Delivery Service",
    "Bill Splitting App Integration",
    "On-Site Maintenance Team",
    "24/7 IT Support",
    "Shared Subscription Services (Netflix, Spotify, etc.)",
  ],
  "Recreation & Community": [
    "Study Room",
    "Recreational Room",
    "Co-Working Space",
    "Fitness Center",
    "Yoga Studio",
    "Game Room (Pool, Ping Pong, etc.)",
    "Movie Theater Room",
    "Communal Library",
    "Podcast Recording Booth",
    "Art Studio",
    "Music Practice Room",
    "Meditation Space",
    "Rooftop Lounge",
    "Community Garden Plots",
  ],
  "Health & Wellness": [
    "On-Site Gym",
    "Sauna",
    "Swimming Pool",
    "Meditation Garden",
    "Spa Services",
    "Mental Health Resources",
    "Group Fitness Classes",
    "Wellness Workshops",
  ],
  Sustainability: [
    "Solar Panels",
    "Energy-Efficient Appliances",
    "Composting System",
    "Rainwater Harvesting",
    "Green Roof",
    "Eco-Friendly Cleaning Products",
    "Sustainable Transportation Options",
  ],
};



export const nearbyPlacesList = 
  {
  "": [
    "Grocery Store",
    "Restaurant",
    "Cafe",
    "Park",
    "Gym",
    "Beach",
    "School",
    "Library",
    "Hospital",
    "Shopping Mall",
    "Bus Stop",
    "Train Station",
    "Pharmacy",
    "Bank",
    "Post Office",
    "Cinema",
  ],
}

